version: '3.9'
services:
  node:
    build:
      context: .
    tty: true
    volumes:
      - ./src:/app
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - '3000:3000'
    command: sh -c "cd src && npm run dev"
